name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build apk
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: build

    - name: Assemble the Release .apk
      run: ./gradlew assembleRelease
    - name: Create and Release the main artifact
      uses: actions/upload-artifact@v3
      with:
        name: osudroid
        path: build/outputs/apk/release/app-release.apk
